$ANSIBLE_VAULT;1.1;AES256
38303063326162633737333664643764323636643732623639393038396332346635303336383335
3738363163373765653035353839383861393039343836610a383530326238643963646465303932
32623535396163636439613936663031626231353065313232666436303730636435306131396135
6264623537653831300a333537386334633831656430373739343964643430653166366262326436
37376638393066343931326631623261366631356139636335313533313635613339623530663065
61373635623462623630383533663933623961353264396461663638653666656365333230336132
64363534653738623532303230326563346566343731356433343835663032396366626161303138
34333237306330323436
