---
- name: Install nginx
  apt:
   name: "{{ nginx_package }}"
   state: present


- name: Deploy Nginx reverse proxy config
  copy:
    # src: nginx.conf.j2
    # dest: /etc/nginx/sites-available/default
    src: index.html
    dest: /var/www/html/index.html
  notify: Restart nginx


- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: true